---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: 通过验证对您的环境、网络访问、登录和Web浏览器的支持、开始使用BlueXP勒索软件保护。 
---
= BlueXP勒索软件保护前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
通过验证您的操作环境、登录、网络访问和Web浏览器是否已准备就绪、开始实施BlueXP勒索软件保护。

要使用BlueXP勒索软件保护、您需要满足以下前提条件：

* NetApp StorageGRID或AWS S3中用于备份目标和访问权限集的帐户
+
请参见 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["AWS权限列表"^] 了解详细信息。

* ONTAP 9.11.1及更高版本
+
** 集群管理员ONTAP权限
** NetApp自主勒索软件保护的许可证、由BlueXP勒索软件保护使用、在内部ONTAP实例上启用、具体取决于您使用的ONTAP版本。请参见 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索软件保护概述"^]。
+

NOTE: 与预览版不同、BlueXP勒索软件保护的常规版本包括NetApp自主勒索软件保护技术的许可证。请参见 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索软件保护概述"^] 了解详细信息。

+
有关更多许可详细信息、请参见 link:concept-ransomware-protection.html["了解BlueXP勒索软件保护"]。



* 在BlueXP中：
+
** 必须在BlueXP中为每个虚拟私有云(Virtual Private Cloud、VPC)或内部区域设置一个BlueXP Connector。请参见 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["BlueXP文档以配置连接器"^]。
+

NOTE: 如果您有多个BlueXP连接器、该服务将扫描除当前显示在BlueXP UI中的连接器之外的所有连接器上的数据。

** 至少有一个活动连接器连接到内部ONTAP集群的BlueXP帐户。所有源环境和工作环境都必须位于同一个BlueXP帐户中。
** 具有用于发现资源的帐户管理员权限的BlueXP用户帐户
** 采用NetApp内部存储的BlueXP工作环境(使用NAS或CIFS协议)
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["标准BlueXP要求"^]





NOTE: 工作环境中不再需要启用BlueXP备份和恢复服务。BlueXP勒索软件保护服务有助于通过设置选项配置备份目标。请参见 link:rp-use-settings.html["配置设置"]。
