---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= BlueXP勒索软件保护的常见问题
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 访问

*什么是BlueXP勒索软件保护URL？*
对于URL、在浏览器中输入： https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] 以访问BlueXP控制台。

*要使用BlueXP勒索软件防护、您是否需要许可证？*

您可以使用以下许可证类型：

* 注册90天免费试用。
* 很快、您将能够通过Amazon Web Services (AWS) Marketplace购买按需购买(PAYGO)订阅。
* 很快、您将能够自带许可证(BYOL)、这是您从NetApp销售代表处获得的NetApp许可证文件(NLL)您可以使用许可证序列号在BlueXP电子钱包中激活BYOL。


*如何启用BlueXP勒索软件保护？*
BlueXP勒索软件保护不需要任何支持。BlueXP左侧导航栏会自动启用勒索软件保护选项。

要开始使用此服务、您需要注册或联系NetApp销售代表、以试用此服务。然后、当您使用BlueXP Connector时、它将包括适用于此服务的功能。

** BlueXP勒索软件保护是否可在标准模式、受限模式和专用模式下使用？**
目前、BlueXP勒索软件保护仅在标准模式下可用。敬请关注更多信息。

有关所有BlueXP服务中这些模式的说明、请参阅 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP部署模式"^]。

**如何处理访问权限？**
只有帐户管理员才能启动服务并发现工作负载(因为这涉及到承诺使用资源)。后续交互可由任何角色完成。

**哪种设备分辨率是最佳的？**
BlueXP勒索软件保护的建议设备分辨率为1、1080或更高。

**我应该使用哪种浏览器？**
任何现代浏览器都能正常工作。



== 与其他服务的交互

*BlueXP勒索软件保护是否了解NetApp ONTAP中的保护设置？*
是的、BlueXP勒索软件保护功能可发现ONTAP中设置的Snapshot计划。

*如果您使用BlueXP勒索软件保护设置策略，您将来是否只需要对此服务进行更改？*
我们建议您通过BlueXP勒索软件保护服务更改策略。



== 工作负载

**工作负载由什么组成？**
工作负载包括单个应用程序实例使用的所有卷。例如、部署在ora3.host.com上的Oracle数据库实例的数据和日志可以分别使用vol1和vol2。这些卷共同构成该Oracle数据库实例的特定实例的工作负载。

*BlueXP勒索软件保护如何划分工作负载数据的优先级？*
数据优先级由创建的Snapshot副本和计划的备份决定。

工作负载优先级由Snapshot频率决定。

link:rp-use-protect.html["了解工作负载优先级或重要性"]。

**已添加新卷，但尚未显示**
如果向环境添加了新卷、请重新启动发现并应用保护策略来保护此新卷。

**信息板未显示我的所有工作负载。可能会出什么问题？**
目前仅支持NFS和CIFS卷。系统会筛选出iSCSI卷和其他不受支持的配置、这些配置不会显示在信息板上。



== 保护策略

* BlueXP勒索软件策略是否与其他类型的工作负载策略共存？*
目前、BlueXP备份和恢复(Cloud Backup)支持每个卷一个备份策略。因此、BlueXP备份和恢复以及BlueXP勒索软件保护共享备份策略。

Snapshot副本不受限制、可以与每个服务分开添加。
