---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= BlueXP勒索软件保护的常见问题
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 部署

*要使用BlueXP勒索软件防护、您是否需要许可证？*

您可以使用以下许可证类型：

* 注册30天免费试用。
* 通过Amazon Web Services (AWS) Marketplace、Google Cloud Marketplace和Microsoft Azure Marketplace (即将推出)购买按需购买(PAYGO)订阅。
* 自带许可证(BYOL)、这是您从NetApp销售代表处获得的NetApp许可证文件(NLL)您可以使用许可证序列号在BlueXP电子钱包中激活BYOL。


*如何启用BlueXP勒索软件保护？*
BlueXP勒索软件保护不需要任何支持。BlueXP左侧导航栏会自动启用勒索软件保护选项。

要开始使用此服务、您需要注册或联系NetApp销售代表、以试用此服务。然后、当您使用BlueXP Connector时、它将包括适用于此服务的功能。

要开始使用BlueXP  勒索软件保护、请单击初始登录页面中的"开始发现工作负载"。

* BlueXP  勒索软件保护是否可在标准模式、受限模式和专用模式下使用？*目前、BlueXP勒索软件保护仅在标准模式下可用。敬请关注更多信息。

有关所有BlueXP服务中这些模式的说明、请参阅 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP部署模式"^]。



== 访问

*什么是BlueXP勒索软件保护URL？*对于URL、在浏览器中输入： https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/ransomware-protection"^] 以访问BlueXP  控制台。

*如何处理访问权限？*只有组织管理员才能启动服务并发现工作负载(因为这涉及到对资源的使用)。后续交互可由任何角色完成。

*什么设备分辨率是最佳的？*BlueXP勒索软件保护的建议设备分辨率为1、1080或更高。

*我应该使用哪种浏览器？*任何现代浏览器都能正常工作。



== 与其他服务的交互

*BlueXP勒索软件保护是否了解NetApp ONTAP中的保护设置？*是的、BlueXP  勒索软件保护功能可发现ONTAP中设置的快照计划。

*如果您使用BlueXP勒索软件保护设置策略，您将来是否只需要对此服务进行更改？*
我们建议您通过BlueXP勒索软件保护服务更改策略。

* BlueXP  勒索软件保护如何与BlueXP  备份和恢复以及SnapCenter进行交互？*

BlueXP  勒索软件防护使用以下产品和服务：

* BlueXP  备份和恢复、用于发现和设置文件共享工作负载的快照和备份策略
* SnapCenter或SnapCenter for VMware、用于发现和设置应用程序和VM工作负载的快照和备份策略。


此外、BlueXP  勒索软件保护功能使用BlueXP  备份和恢复以及适用于VMware的SnapCenter / SnapCenter执行文件和工作负载一致的恢复。



== 工作负载

*工作负载由哪些组成？*工作负载是指应用程序、虚拟机或文件共享。工作负载包括单个应用程序实例使用的所有卷。例如、部署在ora3.host.com上的Oracle数据库实例的数据和日志可以分别使用vol1和vol2。这些卷共同构成该Oracle数据库实例的特定实例的工作负载。

*BlueXP勒索软件保护如何划分工作负载数据的优先级？*数据优先级由创建的Snapshot副本和计划的备份决定。

工作负载优先级(严重、标准、重要)由已应用于与工作负载关联的每个卷的快照频率决定。

link:rp-use-protect.html["了解工作负载优先级或重要性"]。

* BlueXP  勒索软件保护支持哪些工作负载？*

BlueXP  勒索软件保护可识别以下工作负载：Oracle、MySQL、文件共享、VM和VM数据存储库。

此外、如果客户使用的是SnapCenter或SnapCenter for VMware、则这些产品支持的所有工作负载也会通过BlueXP  勒索软件保护进行标识、BlueXP  勒索软件保护可以以工作负载一致的方式保护和恢复这些工作负载。

*如何将数据与工作负载关联起来？*

BlueXP  勒索软件保护可通过以下方式将数据与工作负载关联起来：

* BlueXP  勒索软件保护功能可发现卷和文件扩展名、并将其与相应的工作负载相关联。
* 此外、如果您拥有适用于VMware的SnapCenter或SnapCenter、并且已在BlueXP  备份和恢复中配置了工作负载、则BlueXP  勒索软件保护会发现由适用于VMware的SnapCenter和SnapCenter管理的工作负载及其关联卷。


*什么是"受保护"工作负载？*在BlueXP  勒索软件保护中、如果启用了主检测策略、则工作负载会显示"受保护"状态。目前、这意味着已在与工作负载相关的所有卷上启用ARP。

*什么是"面临风险"的工作负载？*如果工作负载未启用主检测策略、则即使启用了备份和快照策略、它也会处于"风险"状态。

*新卷已添加、但尚未显示*如果已向环境中添加新卷、请重新启动发现并应用保护策略来保护此新卷。

*信息板不会显示我的所有工作负载。可能是什么问题？*目前仅支持NFS和CIFS卷。 系统会筛选出iSCSI卷和其他不受支持的配置、这些配置不会显示在信息板上。



== 保护策略

* BlueXP勒索软件策略是否与其他类型的工作负载策略共存？*
目前、BlueXP备份和恢复(Cloud Backup)支持每个卷一个备份策略。因此、BlueXP备份和恢复以及BlueXP勒索软件保护共享备份策略。

Snapshot副本不受限制、可以与每个服务分开添加。

*勒索软件保护策略需要哪些策略？*

勒索软件保护策略需要以下策略：

* 勒索软件检测策略
* 快照策略


BlueXP  勒索软件保护策略不需要备份策略。

*BlueXP勒索软件保护是否了解NetApp ONTAP中的保护设置？*

是的、BlueXP  勒索软件保护功能可发现在ONTAP中设置的快照计划、以及是否在发现的工作负载中的所有卷上启用了ARP和FPolicy。您最初在信息板中看到的信息是从其他NetApp解决方案和产品中汇总的。

* BlueXP  勒索软件防护是否了解BlueXP  备份和恢复以及SnapCenter中已制定的策略？*

是的、如果您在BlueXP  备份和恢复或SnapCenter中管理工作负载、则这些产品管理的策略将引入BlueXP  勒索软件保护。

*是否可以修改从BlueXP  备份和恢复和/或SnapCenter转移的策略？*

不能、您不能在BlueXP  勒索软件保护中修改由BlueXP  备份和恢复或SnapCenter管理的策略。您可以在BlueXP  备份和恢复或SnapCenter中管理对这些策略所做的任何更改。

*如果ONTAP中存在策略(已在系统管理器中启用，如ARP、FPolicy和快照)，BlueXP  勒索软件保护中是否更改了这些策略？*

否 BlueXP  勒索软件保护不会修改ONTAP中的任何现有检测策略(ARP、FPolicy设置)。

*注册BlueXP  勒索软件保护后，如果您在BlueXP  备份和恢复或SnapCenter中添加新策略，会发生什么情况？*

BlueXP  勒索软件保护可识别在BlueXP  备份和恢复或SnapCenter中创建的任何新策略。

*是否可以从ONTAP更改策略？*

可以、您可以在BlueXP  勒索软件保护中从ONTAP更改策略。您还可以在BlueXP  勒索软件保护中创建新策略并将其应用于工作负载。此操作会将现有ONTAP策略替换为在BlueXP  勒索软件保护中创建的策略。

*是否可以禁用策略？*

您可以使用System Manager UI、API或CLI在检测策略中禁用ARP。

您可以通过应用不包含FPolicy和备份策略的其他策略来禁用它们。
