---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: 通过验证对您的环境、网络访问、登录和Web浏览器的支持、开始使用BlueXP勒索软件保护。 
---
= BlueXP勒索软件保护前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
通过验证您的操作环境、登录、网络访问和Web浏览器是否已准备就绪、开始实施BlueXP勒索软件保护。

要使用BlueXP ransomware protection，您需要满足先决条件。



== 在BlueXP  中

* 使用组织管理Privileges发现资源的BlueXP  用户帐户。
* 一个BlueXP组织，至少有一个活动的BlueXP连接器连接到本地ONTAP集群或者 AWS 或 Azure 中的Cloud Volumes ONTAP 。
* BlueXP  连接器必须使 `cloudmanager-ransomware-protection`容器处于活动状态。
* 至少一个BlueXP工作环境，其中包含NetApp本地ONTAP集群或 AWS 或 Azure 中的Cloud Volumes ONTAPBlueXP ransomware protection支持 NAS（NFS 和 SMB）和 SAN（iSCSI、FC 和 NVMe）协议。
+
** 支持具有ONTAP OS 版本 9.11.1 或更高版本的ONTAP或Cloud Volumes ONTAP集群。
+

NOTE: 仅ONTAP 9.17.1 及更高版本支持 SAN 工作负载。

** 如果您的本地ONTAP集群或 AWS 或 Azure 云中的Cloud Volumes ONTAP尚未加入BlueXP，则您需要一个BlueXP连接器。
+
请参阅 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["了解如何配置BlueXP  连接器"] 和 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["标准BlueXP要求"^]。

+

NOTE: 如果您在一个BlueXP  组织中有多个BlueXP  连接器、则BlueXP  勒索软件保护服务将扫描BlueXP  UI中当前选定连接器以外所有连接器上的ONTAP资源。







== 在ONTAP 9.11.1及更高版本中

* 已在内部ONTAP实例上启用ONTAP One许可证。
* NetApp自主勒索软件保护的许可证、由BlueXP勒索软件保护使用、在内部ONTAP实例上启用、具体取决于您使用的ONTAP版本。请参见 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索软件保护概述"^]。
+

NOTE: 与预览版不同、BlueXP勒索软件保护的常规版本包括NetApp自主勒索软件保护技术的许可证。请参见 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索软件保护概述"^] 了解详细信息。

+
有关更多许可详细信息、请参见 link:concept-ransomware-protection.html["了解BlueXP勒索软件保护"]。

* 要应用保护配置(例如启用自动勒索软件保护等)、BlueXP  勒索软件保护需要对ONTAP集群具有管理员权限。ONTAP集群应仅使用ONTAP集群管理员用户凭据进行登录。
* 如果已使用非管理员用户凭据在BlueXP  中加入ONTAP集群、则必须按照本页面所述登录到ONTAP集群、以必要的权限更新非管理员用户权限。




== 用于数据备份

* NetApp StorageGRID、AWS S3、Azure Blob 或 Google Cloud Platform 中用于备份目标的帐户以及设置的访问权限。
+
有关详细信息、请参见 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["AWS、Azure或S3权限列表"^] 。

* 无需在工作环境中启用BlueXP  备份和恢复服务。
+
BlueXP勒索软件保护服务有助于通过设置选项配置备份目标。请参阅。 link:rp-use-settings.html["配置设置"]





== 在ONTAP工作环境中更新非管理员用户权限

如果您需要更新特定工作环境的非管理员用户权限、请完成以下步骤。

. 登录到BlueXP  并查找需要更新其ONTAP用户权限的工作环境。
. 双击工作环境可查看详细信息。
. 选择“查看其他信息”以显示用户名。
. 使用admin用户登录到ONTAP集群命令行界面。
. 显示该用户的现有角色。输入 ...
+
[listing]
----
security login show -user-or-group-name <username>
----
. 更改用户的角色。输入 ...
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. 返回到BlueXP  勒索软件保护UI以使用它。

